name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: 'docker-compose.test.yml'

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: CI=true npm run test
